version: '3'

services:
  photo-gallery:
    build: .
    ports:
    - "3002:3002"
    depends_on:
    - "mongo"

  # mongo-seed:
  #   build: ./database
  #   depends_on:
  #   - "mongo"

  mongo:
    image: mongo:latest
  