version: '3'

services:
  photo-gallery:
    build: .
    ports:
    - "3002:3002"
    links:
    - mongo
  mongo-seed:
    build: .
    volumes:
    - ./database:/data
  mongo:
    image: mongo:latest
  